/**
 * FROZEN CONTRACT. DO NOT EDIT THIS FILE.
 *
 * Every node in the Petri tree ships a copy of this file, byte for byte.
 * The evolve loop rejects any patch that changes it.
 * The signature of solve() in ./index.ts is frozen with it.
 *
 * The harness NEVER sees the tests. TaskView is built by the task loader, which
 * reads bench/tasks/<id>/task.json, PROMPT.md and starter/ only.
 * It never opens bench/tasks/<id>/test.mjs.
 */

export const HARNESS_ENTRY_VERSION = 1 as const;

export interface SourceFile {
  readonly path: string;      // Relative, inside the task sandbox, e.g. "solution.mjs".
  readonly contents: string;
}

export interface SymbolSpec {
  readonly name: string;      // "chunk"
  readonly signature: string; // "export function chunk(input, size)"
}

/** Everything the harness may see. Never the tests. */
export interface TaskView {
  readonly taskId: string;
  readonly prompt: string;                          // PROMPT.md, verbatim.
  readonly entryFile: string;                       // The file the solution must write.
  readonly exportedSymbols: readonly SymbolSpec[];  // What the tests will import.
  readonly starterFiles: readonly SourceFile[];     // Read-only context. Never tests.
  readonly constraints: readonly string[];
  readonly language: 'javascript';
}

export type Role = 'user' | 'assistant';
export interface ChatMessage { readonly role: Role; readonly content: string; }

export interface ModelRequest {
  /** REQUIRED. Names the call site, e.g. "draft" or "repair#1". Labels must be distinct. */
  readonly label: string;
  readonly messages: readonly ChatMessage[];
  readonly system?: string;
  readonly maxTokens?: number;
  readonly temperature?: number;
  readonly stopSequences?: readonly string[];
}

export interface ModelResponse {
  readonly text: string;
  readonly stopReason: 'end_turn' | 'max_tokens' | 'stop_sequence';
  readonly inputTokens: number;
  readonly outputTokens: number;
}

/** The only way a harness reaches a model. */
export interface ModelClient { complete(req: ModelRequest): Promise<ModelResponse>; }

export interface BudgetState {
  readonly callsUsed: number; readonly callsLeft: number;
  readonly tokensUsed: number; readonly tokensLeft: number;
  readonly msLeft: number;
}

/** The runner enforces the budget. The harness may read it. It may never raise it. */
export interface Budget {
  readonly maxCalls: number;
  readonly maxTokens: number;
  readonly maxWallMs: number;
  state(): BudgetState;
}

/** The runner owns the trace. A harness cannot forge it. */
export interface Logger { event(kind: string, data?: Record<string, unknown>): void; }

export interface HarnessContext {
  readonly model: ModelClient;
  readonly budget: Budget;
  readonly log: Logger;
  readonly rng: () => number;  // Seeded from the run seed. Deterministic.
  readonly now: () => number;  // A frozen clock.
}

export interface Solution {
  readonly files: readonly SourceFile[];
  readonly notes?: string;
}

/** ModelClient.complete rejects with this when the harness overspends. */
export class BudgetExceededError extends Error {
  readonly kind = 'budget-exceeded';
  constructor(public readonly what: 'calls' | 'tokens' | 'wall', message: string) {
    super(message);
    this.name = 'BudgetExceededError';
  }
}
